### ISSUE TITLE
Add ignore argument to join

### ISSUE THREAD

**Issue by pauldix** [influxdata/ifql#105]
Should work like it does in `group`

**Comment by jsternberg** [comment]
This will likely be useful for the transpiler. As an example query:

```
SELECT a, b FROM db0..foo
```

Might get transpiled to this:

```
val1 = from(db: "db0") |> range(...) |> measurement(name: "foo") |> field(name: "a")
val2 = from(db: "db0") |> range(...) |> measurement(name: "foo") |> field(name: "b")
join(tables: {a: val1, b: val2}, except: ["_field"])
```

This mostly matches what the influxql query engine does. It creates a cursor for each measurement and field and the joins them together based on measurement and series key. The only caveat is this join also needs to be an outer join.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/338)
