### ISSUE TITLE
Weighted Percentiles

### ISSUE THREAD

**Issue by samhatchett** [influxdata/ifql#134]
I'm really liking the new IFQL stuff - also wondering about future support for better/more statistical summaries.

An example is [Weighted Percentiles](https://en.wikipedia.org/wiki/Percentile#The_weighted_percentile_method). My domain of interest is infrastructure monitoring of an unusual sort - having to do with computing the chemistry and consumption of treated municipal drinking water. There's probably a good analogy for IT infrastructure, but that's unfortunately not my area of expertise. 

I have a bunch of locations where water is being consumed (Liters/second) in a time-varying fashion, and I have a time-varying chemical concentration of some constituent in the water (milligrams/Liter) at each of these locations. I would like to compute (for instance) the 75th percentile concentration consumed for any discrete volume, every 5m. Said another way, "Across the entire system, 75% of Liters consumed had chemical concentration less than X". That is a special calculation - percentile concentration weighted by rate of consumption. I don't think that is currently possible within the current set of functions, although using 2 variables and a join, one could deliver the result in terms of a derived metric. But delivering what I described would involve joining two queries, multiplying the results together to form a third "weighted column" (keeping the intermediate joined table), selecting a .percentile() on that third column, and returning the value of a different column at the end of it all. Alternatively, there is a method that only involves sorting and taking a cumulative probability.

My current approach is to implement this as a Python plugin to Kapacitor, as I can imagine no simpler way, even given the flexibility of the new query language. But I would love to be wrong ;)

**Comment by nathanielc** [comment]
@samhatchett We have been think about how to do exactly this for a while. How does this IFQL syntax read?

```
var rate = // ... select the rate data
var concentration = // ... select the concentration data

weightedPercentile(weights: rate, values: concentration, on: ["host"])
```

The above is just a proposal. It says compute the weighted percentile using `rate` as the weights and `concentrations` as the values. The `on` parameter is because the function will need to do a join in order to pair up the weights and values. Under the hood the `weightedPercentile` function can leverage the existing join code and then perform the weighted percentile computation on the result of the join.

Thoughts? This is just a proposal at the moment, but is something we have been thinking about for a while. Does the above syntax read well to you? Is it clear what is being computed and how?

Another example could be computing the covariance of series like:

```
covariance(series:[a,b])
```

**Comment by samhatchett** [comment]
@nathanielc this looks really great. Glad that others are thinking about this feature! The named parameters really prove their purpose here.

Covariance would be very nice to have as well.

**Comment by nathanielc** [comment]
@samhatchett FWIW we now have the pieces in place to be able to do something like this. Covariance has been added as a first example. Are you interested in submitting a PR for a weightedPercentile function? If so I can give you some pointers and get you started in the right direction.

**Comment by samhatchett** [comment]
Sure, I’m game. Pointers welcome. Will let you know if I find myself in the deep end.

**Comment by nathanielc** [comment]
💯! You have probably figured it out already, but take a look at `functions/covariance.go` as it has the mechanics in place. The basic idea is you define a transformation that does the actual work. Then define a helper builtin function that does an automatic join preparing the value columns that you need for the transformation.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/335)
