### ISSUE TITLE
[RFC] How should we express values of series in IFQL?

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#170]
# How should we express accessing values of a series in IFQL?

There are two contexts under which a user may want to reference the value of a series.

1. When filtering the raw data to be read from the storage API
2. When applying an expression to the records of a table 

Ideally these two cases map to the same thing, meaning we can represent the raw data in the storage API as a table. This way the user doesn't have to think of them as separate.

We must also consider that it might be possible for a records of a table to have more than one value, even though this is not possible for series stored in InfluxDB.

To illustrate the various solutions and contexts, lets examine is a contrived example:

Given three metrics: cpu usage idle, request count and request error count, we want to determine the covariance between cpu usage and request count only when the error count is greater than some threshold. A fake user story here would be that a use wants to try and find a correlation between cpu usage and request rate when there are elevated error rates.

NOTE:  The covariance function is being used here because its a function that needs to consume multiple values on the same record. See #134 for a similar function that needs to process multiple values at once. The covariance function doesn't exist yet, partially because we haven't solved this problem. As such we will show how covariance can be implemented in IFQL using basic primitives.

The covariance is defined as the mean of (x - meanX)(y - meanY) for all (x,y) pairs.

The following sections demonstrate a possible solution to the problem using the above example.

To be honest I kind of expect these examples to be a bit confusing. That is in part at least to the fact that I haven't found a consistent solution to the issue, so all of the examples are a bit rough.

## Use the `_value` special name

When the user hasn't provided a name for the value of a series use the special name `_value`.

```javascript
var cpu = from(db:"telegraf")
    .filter(f: r => r["_measurement"] == "cpu" and r["cpu"] == "cpu-total" and r["_field"] == "usage_idle" )
    .range(start:-1h)

var reqCount = from(db:"mydb")
    .filter(f: r => r["_measurement"] == "requests" and r["_field"] == "count" )
    .range(start:-1h)

var errCount = from(db:"mydb")
    .filter(f: r => r["_measurement"] == "requests" and r["_field"] == "error_count" and r["_value"] > 0)
    .range(start:-1h)

// Perform inner join so that we only keep the request count points that have an non-zero error count
var reqCountWithErrors = join(tables:[reqCount, errCount], on:["service"], f: (reqs, errs) => reqs.values["_value"])

function covariance(x, y) {
  var meanX =  x.mean()
  var meanY =  y.mean()

  var n =  x.count()

  // join the x, y tables an produce records with values named 'x' and 'y' respectively.
  join(tables:[x,y], f: (x,y) => {x: x, y: y})
    // We could push this map call up into the join, but I am leaving it separate to demonstrate creating named values.
    .map(f: r => (r["x"] - meanX)*(r["y"] - meanY))
    .sum()
    .map(f: r => r["_value"] / n)
}

// Compute the covariance with cpu
covariance(x: reqCountWithError, y:cpu)
```

### Pros:

* Short syntax
* Doesn't require the user to distinguish between tags and values.

### Cons:

* What if the data has a tag named `_value`?
* Blurs the lines between tags and values.

## Use `.tags` and `.values` on the record object

Separate tags and values into different sub namespaces of the record object.

```javascript
var cpu = from(db:"telegraf")
    .filter(f: r => r.tags["_measurement"] == "cpu" and r.tags["cpu"] == "cpu-total" and r.tags["_field"] == "usage_idle" )
    .range(start:-1h)

var reqCount = from(db:"mydb")
    .filter(f: r => r.tags["_measurement"] == "requests" and r.tags["_field"] == "count" )
    .range(start:-1h)

var errCount = from(db:"mydb")
    .filter(f: r => r.tags["_measurement"] == "requests" and r.tags["_field"] == "error_count" and r.values["_value"] > 0)
    .range(start:-1h)

// Perform inner join so that we only keep the request count points that have an non-zero error count
var reqCountWithErrors = join(tables:[reqCount, errCount], on:["service"], f: (reqs, errs) => reqs.values["_value"])

function covariance(x, y) {
  var meanX =  x.mean()
  var meanY =  y.mean()

  var n =  x.count()

  join(tables:[x,y], f: (x,y) => {x: x, y: y})
    .map(f: r => (r["x"] - meanX)*(r["y"] - meanY))
    .sum()
    .map(f: r => r.values["_value"] / n)
}

// Compute the covariance with cpu
covariance(x: reqCountWithError, y:cpu)
```

### Pros:

* Keeps the lines between tags and values clear.

### Cons:

* Longer syntax
* Requires the user to distinguish between tags and values.
* There is stutter when there is only one value, which is the most common case: `r.values["_value"]`.

### Questions

* What should the name of the value be if its coming from storage or no name was given in an arrow expression?

## Assume there is only ever one value that is accessed via the `.value()` function

```javascript
var cpu = from(db:"telegraf")
    .filter(f: r => r["_measurement"] == "cpu" and r["cpu"] == "cpu-total" and r["_field"] == "usage_idle" )
    .range(start:-1h)

var reqCount = from(db:"mydb")
    .filter(f: r => r["_measurement"] == "requests" and r["_field"] == "count" )
    .range(start:-1h)

var errCount = from(db:"mydb")
    .filter(f: r => r["_measurement"] == "requests" and r["_field"] == "error_count" and r.value() > 0)
    .range(start:-1h)

// Perform inner join so that we only keep the request count points that have an non-zero error count
var reqCountWithErrors = join(tables:[reqCount, errCount], on:["service"], f: (reqs, errs) => reqs.value())

function covariance(x, y) {
  var meanX =  x.mean()
  var meanY =  y.mean()

  var n =  x.count()

   // here we have to push the map up into the join as we don't have a choice
  join(tables:[x,y], f: (x,y) => (x.value() - meanX)*(y.value() - meanY))
    .sum()
    .map(f: r => r.value() / n)
}

// Compute the covariance with cpu
covariance(x: reqCountWithError, y:cpu)
```

### Pros:

* Short syntax
* Keeps the lines between tags and values clear.
* There is only ever a single value.

### Cons:

* Requires the user to distinguish between tags and values.
* It's not always possible to assume that there is only one value. For example #134 needs two values, a weight, and a generic value, to compute a weighted percentile. As such we need a way to pass two values into the `weightedPercentile` function as it can't be represented as natively in IFQL primitives. If we can solve this issue I think that makes this the best option.

## Summary

This probably brings up more questions than answers at this point, but I wanted to discuss the issue in its complete context.

Some general questions:

* Do we want to make the distinction between tags and values a prominent aspect of the language? Or do we want to treat records as tuples and let the user keep track of the meaning of each column?
* Can all cases where you might want two values, be reduced to a map expression that combines the values some how? Or how else can we pass a record with two values to a function?

Thoughts? Suggestions?

**Comment by cryptoquick** [comment]
With regards to the `.value()` method syntax I suggested, I think you could also have a `.values()` method that returns a value list instead of a single value. You could have both, with value being sugar for `.values()[0]`.

**Comment by nathanielc** [comment]
I like the idea of supporting sugar for the common case of having a single value. How would that work in the case where `values` is an object and not an arrary? Just throw an error if there are more than one values? I prefer things to be named instead of numerically indexed.

**Comment by cryptoquick** [comment]
An object would be a value, which I suppose would be accessible through the value() method as well. Here's how I suppose these cases would be handled:

**access single value or single value that is an object**
`.value()` - can return either a type primitive or an object with many named properties.
Another option is to have a `.valueOf()` method for object values, and `.value()` for type primitive values, but an object could be considered a sort of value as well.

For example:
```
// Access xyz object property from a value expected to be an object
r.value().xyz
```

**access multiple values**
`.values()` - returns an array of values

Either way, once the value(s) are available to the context, they can be accessed and used.

**Comment by nathanielc** [comment]
For now we have gone with the simple `r._value` syntax. We can revisit later as we kick the tires on the implementation.

Closing the issue now.
