### ISSUE TITLE
Discussion Functions vs Chain Methods tension.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#193]
Now that we have support for functions I am beginning to notice a small tension between what is a chaining method and what is a function.

For example a query can be rewritten to make heavy use of functions. Possibly moving the functions into their own package (but that is irrelevant to this discussion).

Query not using functions"
```

cpu = from(db:"telegraf")
    .filter(fn: (r) =>
          r._measurement == "cpu" 
          and r._field == "usage_idle" 
          and r.cpu == "cpu-total")

mem = from(db:"telegraf")
    .filter(fn: (r) => r._measurement == "mem" and r._field == "used_percent")

join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

Rewriting the query looks like this:
```
fromT = () => from(db:"telegraf")
measurement = (t, m) => t.filter(fn: (r) => r._measurement == m)
field = (t, field) => t.filter(fn: (r) => r._field == field)

cpu = field(t:measurement(t:fromT(), m:"cpu"), field:"usage_idle")
    .filter(fn: (r) => r.cpu == "cpu-total")
mem = field(t:measurement(t:fromT(), m:"mem"), field:"used_percent")


join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

Notice that the function chaining starts to be more about arguments then about function chaining.

As libraries of IFQL functions grow, it will start to loose its chaining syntax, and it will be confusing to new users what is and isn't chainable.

The tension arises because there is no way to define a new chaining method, or indicate that a function can be used as a chaining method. 

I have a few ideas for how this could be addressed but I'd like to hear others thoughts first.

**Comment by desa** [comment]
What about dot being pipe for data. Making it something like the [threading macro](https://clojure.org/guides/threading_macros) from lisp or [pipe](https://elixirschool.com/en/lessons/basics/pipe-operator/) from elixir.

So then both the chaining version and the compositional version are valid. Which is pretty common in functional languages.

**Comment by nathanielc** [comment]
I like that idea, currently the implementation is treating like true function chaining, where the previous function has to return a value, and you call properties on that function. I think we can make it work like a pipe operator. 

Follow up question, from the Elixir docs.

> The pipe operator |> passes the result of an expression as the first parameter of another expression.

Since we do not have positional arguments, i.e. everything is a keyword how do we make that clear? Do we just use a special named keyword argument like `table` or do we define positions are the order in which they are defined in the function definition?

**Comment by desa** [comment]
I think just have a special named keyword. Would it be possible for the QE to be able to tell which argument is a table? Maybe some kind of type inference?

**Comment by nathanielc** [comment]
We don't really have type inference, but we can check types at runtime. At least not in the current implementation, it would be nice to investigate what it would take to have completely static type inference.

**Comment by nathanielc** [comment]
Another follow up question, once we define `.` as the pipe operator that passes the previous result as the `table` arg to the next expression how does that work when we want `.` to mean member lookup?

Example:

```
import "telegraf" =1.0.0

telegraf.from().range(start:-1m)
```

Seems like the `.` in `telegraf.from` means something quite different from the `.` in  `from().range(start:-1m)`. Thoughts?

**Comment by desa** [comment]
We'd need another symbol for name spacing. Clojure does `/` so it'd be

```
import "telegraf" =1.0.0

telegraf/from().range(start:-1m)
```

Don't know if I like that for us. I'm looking to see what some of the other functional languages do.

**Comment by desa** [comment]
After a quick search, it looks like other functional languages don't quite have this issue because `.` means lookup.

**Comment by nathanielc** [comment]
Yeah, I discovered that as well. 

In summary we are proposing adding a pipe operator whose behavior is defined as passing the previous result as the `table` argument to the next function call. The pipe operator is different from the member lookup operator.

Note that member lookup arises primarily in two places, accessing exported variables from imported packages and accessing properties of records in filter and join functions.  Accessing properties of records is going to be quite common, i.e `filter(fn: (r) => r._value == 5 and r._measurement == "cpu")`.  Both `.` in that string are member lookup operators.

I think that for clarity we must use `.` for the member lookup operator.

That means we have two options: The pipe and member lookup operators are the same, and the parser can distinguish them based on context, or we use different operators.

I am going to see if I can't get the parser to understand that the pipe operators exist only in the context of call expressions.

**Comment by nathanielc** [comment]
OK, its not going to be possible to use the same symbol for both operators. Take for example:

```
foo = bar()

// Here the `.` means pipe 
foo.count()
```


```
import "foo" =1.0.0

// Here the `.` means member lookup
foo.from()
```

Since both examples have the expression `<identifier>.<identifier>()` but mean very different things we are going to need different operators to distinguish them.

So which symbol should we use for the pipe operator? A natural choice is the `|` symbol. But we initially got some push back on using `|` everywhere in IFQL.


Rewriting the initial example now looks like this:

```
fromT = () => from(db:"telegraf")
measurement = (t, m) => t.filter(fn: (r) => r._measurement == m)
field = (t, field) => t.filter(fn: (r) => r._field == field)

cpu = fromT() | measurement(m:"cpu") | field(field:"usage_idle") | filter(fn: (r) => r.cpu == "cpu-total")
mem =  fromT() | measurement(m:"mem") | field(field:"used_percent")


join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

It reads much better to me. 

## Summary 

In summary what is being proposed it to throw out the idea of function chaining, and rather introduce function piping. There is a subtle but important difference.  Function chaining calls functions which are properties of the returned value. Function piping calls the next function with the previous value as the `table` argument. Since it is not possible to define new properties of the `table` type it is not possible to call user defined functions as chaining function calls of tables, thus causing awkward nested function calls. Conversely it is possible to pipe function calls.


## P.S.

One final example that illustrates the need for having different operators

Say the above functions instead of being defined in the same script came from a package called `telegraf`
```
package telegraf

from = () => from(db:"telegraf")
measurement = (t, m) => t.filter(fn: (r) => r._measurement == m)
field = (t, field) => t.filter(fn: (r) => r._field == field)
```

```
import "telegraf" =1.0.0

cpu = telegraf.from() | telegraf.measurement(m:"cpu") | telegraf.field(field:"usage_idle") | filter(fn: (r) => r.cpu == "cpu-total")
mem =  telegraf.from() | telegraf.measurement(m:"mem") | telegraf.field(field:"used_percent")


join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

Clearly the `telegraf.from() | ... ` makes it clear that `.` and `|` are doing different things. Otherwise it would look like this:
```
cpu = telegraf.from().telegraf.measurement(m:"cpu").telegraf.field(field:"usage_idle").filter(fn: (r) => r.cpu == "cpu-total")
```

Which doesn't really make sense.

**Comment by desa** [comment]
Another possibility for look up could be `#`

The example would be

```
import "telegraf" =1.0.0

cpu = telegraf#from().telegraf#measurement(m:"cpu").telegraf#field(field:"usage_idle").filter(fn: (r) => r.cpu == "cpu-total")
mem =  telegraf#from().telegraf#measurement(m:"mem").telegraf#field(field:"used_percent")


join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

alternatively we could use what elixir and elm do `|>`

```
import "telegraf" =1.0.0

cpu = telegraf.from() |> telegraf.measurement(m:"cpu") |> telegraf.field(field:"usage_idle") |> filter(fn: (r) => r.cpu == "cpu-total")
mem =  telegraf.from() |> telegraf.measurement(m:"mem") |> telegraf.field(field:"used_percent")


join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

**Comment by nathanielc** [comment]
I do like `|>` as well. 

Note that using `#` means this:

```
cpu = telegraf#from().telegraf#measurement(m:"cpu").telegraf#field(field:"usage_idle").filter(fn: (r) => r#cpu == "cpu-total")
```

See the `r#cpu` bit? I am not a fan of that.

**Comment by desa** [comment]
> See the r#cpu bit? I am not a fan of that.

ah yeah, thats no good.

**Comment by stuartcarnie** [comment]
I really like `|>`. It is an extension of what we know already as pipe (in shells), providing a hint to how data flows. It is also familiar to those coming from functional languages like F# • http://theburningmonk.com/2011/09/fsharp-pipe-forward-and-pipe-backward/

the `.` operator also well known as a namespace delimiter.

**Comment by fntlnz** [comment]
The pipe forward operator seems a good fit when doing function composition, also it is a recognized operator in multiple languages. My only concern is if function composition can be always done in ifql. (Don’t know the answer)

**Comment by nathanielc** [comment]
@fntlnz Thanks for the feedback.

> My only concern is if function composition can be always done in ifql. (Don’t know the answer)

Do you mean being able to use the pipe forward operator for any function not just function that accepts a table argument? If so I am also concerned that supporting such a specific feature would be confusing. Maybe we need to explore what it looks like to support pipe forward generally.

**Comment by fntlnz** [comment]
I'll try to explain with an example, just to share more and understand if we are on the same path.

If I define two custom `map` and `filter` functions (not very different signature in ifql but, you know),
 with pipe forward I would be able to apply any function to the partial result of the previous operation.

Like this example:
```ifql
filter = (fn) => fn(r) //returns bool
map = (fn) => fn(r) //returns int
[1, 2, 3, 4, 5, 6]
    |> filter(fn: (r) => r % 2 == 0)
    |> map(fn: (r) => r * 2)
```

@nathanielc Is that the same?

**Comment by lukevmorris** [comment]
@fntlnz It seems to me, based on the discussion above, that you'd have to define your custom `filter` and `map` function as follows:

```
filter = (table, fn) =>
  // for each "item" in table
  fn(item)

map = (table, fn) =>
  // for each "item" in table
  fn(item)
```

These would be constructed with the understanding that the pipe operator always passes the previous result as the `table` keyword in the subsequent function call.

```
[1, 2, 3, 4, 5, 6]
|> filter(fn: (r) => r % 2 == 0)
|> map(fn: (r) => r * 2)
```

Here, `[1, 2, 3, 4, 5, 6]` would be understood to be a "table".

**Comment by lukevmorris** [comment]
Just some notes:

In Elixir, the convention is that the pipe operator passes the previous result as the _first_ argument in the subsequent function call. Given `isEven = fn(x) -> rem(x, 2) == 0 end`, these two are equivalent:
```
[1, 2, 3, 4, 5] |> Enum.filter(isEven)
Enum.filter([1, 2, 3, 4, 5], isEven)
```

In Elm, the convention is (approximately) that the pipe operator passes the previous result as the _last_ argument in the subsequent function call. Given `isEven x = x % 2 == 0`, these two are equivalent (ignoring whitespace):
```
[1, 2, 3, 4, 5] |> List.filter isEven
List.filter isEven [1, 2, 3, 4, 5]
```

**Comment by nathanielc** [comment]
@fntlnz  I had a similar concern, and like @lukevmorris points out based on the current definition you would have to use the `table` keyword argument name, which is awkward and very confusing. 

The basic issue is that IFQL doesn't have positional arugments, so we need a way to define which argument is supplied via the pipe forward argument. 

The first option was to hardcode it as the `table` argument, but that is inflexible.
What about actually naming the argument in the operator syntax like this:

```
|identifier>
```

Using the previous example:

```
filter = (fn,r) => fn(r) //returns bool
map = (fn,r) => fn(r) //returns int
[1, 2, 3, 4, 5, 6]
    |r> filter(fn: (r) => r % 2 == 0)
    |r> map(fn: (r) => r * 2)
```

Or  using a table based example

```
import "telegraf" =1.0.0

cpu = telegraf.from()
    |t> telegraf.measurement(m:"cpu")
    |t> telegraf.field(field:"usage_idle")
    // Maybe we should have the keyword argument be `t` for builtin functions?
    |table> filter(fn: (r) => r.cpu == "cpu-total")

mem =  telegraf.from()
    |t> telegraf.measurement(m:"mem")
    |t> telegraf.field(field:"used_percent")


join(tables:{cpu:cpu, mem:mem}, on:["host"], fn: (t) => t.cpu._value / t.mem._value)
```

This is a break for standard Elixir etc but I think it maps the concepts well to a space where there are only keyword arguments.

**Comment by fntlnz** [comment]
@lukevmorris thanks for clarifying, I lost that point!

> The basic issue is that IFQL doesn't have positional arugments, so we need a way to define which argument is supplied via the pipe forward argument.

@nathanielc  Are you thinking about currying? 😌 

Naming in the operator seems a good compromise, we could call it "named pipe forward operator" 


> This is a break from how Elixir and Elm work but I think it maps the concepts well to a space where there are only keyword arguments.

It's a DSL so I wouldn't compare it to a more generic programming language which can (need to) implement any sort of abstraction. However I think that giving "familiar" constructs is a nice idea.

**Comment by nathanielc** [comment]
@fntlnz 

> Are you thinking about currying? 😌

It has come up a few times, personally I haven't been convinced it is needed, but am willing to listen to any ideas. Although lets leave a currying discussion for a different issue. I want to keep this issue focused on how to solve the nested functions problem.

**Comment by pauldix** [comment]
Let me start be restating what I think the original problem was: There's no way to define a new function in the language that can be chained. This is a result of not being able to reference the passed in chained item in your function. This is also why we see every one of these function definitions taking the input as an argument.

The problem with namespacing is really just a confounding factor. I think it's trivial to disambiguate from a function to a namespace even if you overload the `.` operator. The reason is that a function always requires the parens for the call, even if there are no arguments. Eg:

```
import "telegraf"

from().telegraf.measurement() // valid
from().telegraf().measurement() // invalid
```

Or a script like this:

```
telegraf = (t) => {
  // do stuff
}

from().telegraf(t:foo) // valid
from().telegraf.measurement() // invalid
```

It does mean that package names can't collide with variable names in the script, but I don't think that's a big problem.

Going back to the original problem, only the Pipe Forward Operator with Name Defined at Function Definition seems to solve the real underlying problem. However, I don't think it's necessary to add the pipe forward syntax. Only the function definition syntax would need to be changed.

I saw in the discussion that the standard shell scripts use `|` and the pipe forward feels familiar because of that. However, the problem of referencing your inputs in shell scripts is solved by having a magic global variable that gets referenced.

For functions that we've implemented in Go we're able to reference the input (or specify that it can't be chained) and specify required and optional arguments. Maybe we should just be looking at extending the function definition syntax to add these features?

At first glance I'm a little allergic to the pipe forward syntax, but that's mostly because it looks foreign to me. I think it's a priority to keep the language easy to read, which is one of the reasons we've copied much of JS's syntax, which is probably more widely used than anything at this point. The functional languages have generally not been paragons of readability and approachability for newbies or beginners.

Need to stew on it for a little bit and come back to it after a day or two.

**Comment by bohnman** [comment]
I agree with @pauldix.  I think having 2 ways of calling functions depending on whether or not a function is chainable puts unnecessary cognitive burden on the library user.  This burden should be pushed to the library provider.

If we use javascript as the inspiration again, it provides two ways to extend an existing library

1) Add a new method to a class, which is globally available.  This is useful for library providers.

```
// library file
Stream.prototype.doSomething = term => {
    return this.filter(r => r["bar"] == term)
}
```

```
import "library"

from("foo").doSomething("baz")
```

2) Add a new method to an instance, which is only available for that instance.  This is useful for quick and dirty inline functions

```
var s = from("foo");

s.doSomething = term => {
    return this.filter(r => r["bar"] == term)
}

s.doSomething("baz")
```

Both can be used as follows

Food for thought

**Comment by nathanielc** [comment]
@bohnman We agree that we don't want the users to have to think about chainable vs not chainable functions. Thanks for the feedback, we have been discussing this issue at length. One concern we had with mutating the original type is that importing packages have side effects instead of exposing new functionality directly. We had lots of discussion yesterday and I think we are close to a final solution, I'll post an update in a bit.

**Comment by nathanielc** [comment]
All,

We have discussed this at length have come to a consensus. We will use a pipe forward operator `|>` to make calling long chains of nested functions easy and more readable. Using the pipe forward operator is a natural fit because an IFQL query describes a flow of transformations on data. 

There will be no concept of function chaining in the traditional OO sense. We do not want to expose types and inheritance as constructs in IFQL. As such solutions using traditional OO concepts are not possible. An IFQL query describes a flow of transformations on generic data, not a set of operations to apply to specific classes.

Function definitions must specify which single argument of their arguments can be used for piped expressions. This places the burden on library developers and not consumers of libraries to understand how functions can be piped. A new user need only learn the `|>` syntax and nothing more in order to get up and running with IFQL.

Some examples:

```
// The following two lines are equivalent expressions
range(t:from(db:"telegraf"), start:-1m)
from(db:"telegraf") |> range(start:-1m)

// Range function definition
// `t<-` indicates that piped expressions are applied as the `t` argument to the function.
range(t<-, start, stop=now)
```


```
import "telegraf" =1.0.0

cpu = telegraf.from()
    |> telegraf.measurement(m:"cpu")
    |> telegraf.field(field:"usage_idle")
    |> filter(fn: (r) => r.cpu == "cpu-total")

mem =  telegraf.from()
    |> telegraf.measurement(m:"mem")
    |> telegraf.field(field:"used_percent")
```

where the fictional `telegraf` package has been defined as:

```
package telegraf

from = () =>
     from(db:"telegraf")

measurement = (t<-, m) =>
    t.filter(fn: (r) => r._measurement == m)

field = (t<-, field) =>
    t.filter(fn: (r) => r._field == field)
```


Specifying the pipe-able argument at function definition is a bit more limiting compared to specifying the argument at call time, but it allows the call time expressions to be simpler. There are currently no motivating examples for why being able to change which argument is piped at call time adds value. By defining the pipe-able argument at function definition we simplify the call time syntax and constrain the space where piped expressions can be used without loosing any value. In addition this is similar to how more traditional functional languages operate since only a single argument can be used in those language, (typically the first arg).

**Comment by pauldix** [comment]
@nathanielc looks great, that captures everything we talked about.

**Comment by pauldix** [comment]
One last thought to chime in on this thread. Since parameters with default values are specified like `end=now` for example, would it be more consistent to have:

```
field = (t=<-, field) =>
    t.filter(fn: (r) => r.field == field)
```

Looks a little weird, but I'm just putting it up here for debate.

**Comment by nathanielc** [comment]
@pauldix Hmm, at first I was like no, `t` is a required parameter so don't make it read like one. But after thinking about it, I kind of like it. It reads like `t`'s default value is something special.  The special value is the result of a piped expression. It communicates that not all call expressions for the function will specify `t` which is true. I don't have a strong opinion either way but I like the idea.
