### ISSUE TITLE
Add support using intermediate results in filter functions 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#200]
```SQL
SELECT mean(value)
FROM cpu
WHERE time > now() - 24h
GROUP BY time(1h), host
SORDER max(value) 5m desc
SLIMIT 5
```
The equivalent IFQL query is:

```
topN = from(db:"telegraf")
|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_idle")
|> range(start:-5m)
|> group(by:["host"])
|> max()
|> sort(cols:["_value"])
|> limit(n:5)

from(db:"telegraf")
|> filter(fn: (r) => r.host in topN.host and r._measurement == "cpu" and r._field == "usage_idle")
|> range(start:-24h)
|> window(every:1h)
|> mean()
```

https://github.com/influxdata/influxdb/issues/1819
https://github.com/influxdata/influxdb/issues/7894
https://github.com/influxdata/influxdb/issues/2157

**Comment by szibis** [comment]
Why this is so much complicated to take topN/MaxN results ?
```
from(db:"telegraf")
|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_idle")
|> range(start:-5m)
|> max()
|> group(by:["env"])
|> sort(cols:["_value"])
|> limit(n:5)
```
As I undestand - filter cpu measurement to only cpu_usage field from range of 5 minutes. Then taking max and group everything by host then limiting to 5 results. 

I get
```
measurement,env=production value=1.0204081630077233 1517353487650127066
measurement,env=production value=1.0309278361534955 1517353487650127066
measurement,env=production value=1.0526315794713985 1517353487650127066
measurement,env=production value=1.2345679006911723 1517353487650127066
measurement,env=production value=1.8518518498307526 1517353487650127066
measurement,env=staging value=2.325581395016815 1517353487650127066
measurement,env=staging value=2.5834230353091097 1517353487650127066
measurement,env=staging value=2.884615384487571 1517353487650127066
measurement,env=staging value=3.3333333335489175 1517353487650127066
measurement,env=staging value=3.645833337375532 1517353487650127066
measurement,env=sandbox value=56.84210520020978 1517353487650127066
measurement,env=sandbox value=56.84210520020978 1517353487650127066
measurement,env=sandbox value=87.50000000287208 1517353487650127066
measurement,env=sandbox value=90.24390243711991 1517353487650127066
measurement,env=sandbox value=91.66666666262446 1517353487650127066
```

What we need is to have maxN/TopN from the whole set of data after sorting/grouping/limiting just like in graphite in one simple query - http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.highestMax

Now I would like to have top2/max2 like this in one query:
```
measurement,env=staging value=2.325581395016815 1517353487650127066
measurement,env=staging value=2.5834230353091097 1517353487650127066
measurement,env=staging value=2.884615384487571 1517353487650127066
measurement,env=staging value=3.3333333335489175 1517353487650127066
measurement,env=staging value=3.645833337375532 1517353487650127066
measurement,env=sandbox value=56.84210520020978 1517353487650127066
measurement,env=sandbox value=56.84210520020978 1517353487650127066
measurement,env=sandbox value=87.50000000287208 1517353487650127066
measurement,env=sandbox value=90.24390243711991 1517353487650127066
measurement,env=sandbox value=91.66666666262446 1517353487650127066
```
How can we get such results ?

Maybe there is something wrong with my tests, but simplicity is power. That's why graphite api is still alive and growing.

**Comment by nathanielc** [comment]
@szibis Thanks for the detailed example. The query in the issue description is not currently implemented.

There are two steps in the query:

1. First select the top 5 hosts from the last 5m of data based on max cpu.
2. Select the mean cpu grouped by 1h for the last day only for the top 5 hosts selected in step 1.

There really are two queries being performed, hence the two part query. Currently the first step is possible as you have shown. The second step needs to be designed and implemented.

Specifically we need to add support for this bit in the second query's filter expression:

```
 r.host in topN.host 
```

The idea here is that the result of a previous query can be used in the filtering of subsequent queries using the `in` operator.

An alternate syntax could be this to make it more clear we are consuming the column vector from the table topN.

```
 r.host in column(table: topN, c:"host")
```

Does that answer your question about how to do the second query you demonstrated?

As for the complexity of the query, common behaviors like this can be encapsulated in functions for easy reuse. This is what graphite is doing as well. From their docs referring to highestMax:

> This is an alias for highest with aggregation max.

In IFQL we can do something similar:

```
topN = (n, table=<-) =>
    table  
      |> max()
      |> sort(cols:["_value"])
      |> limit(n:5)

from(db:"telegraf")
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_idle")
  |> range(start:-5m)
  |> group(by:["env"])
  |> topN(n:5)

```

**Comment by szibis** [comment]
Yes great. 

My question about complexity was about reusing topN, which is defined somewhere and when we do the ifql query by API call for example in the console then we can lookup and use this topN(n:5) in one query.
This is all powerful especially with kapacitor.

This is connected with chronograf implementation of query builder https://github.com/influxdata/chronograf/issues/1966 and how you plan to implement this in grafana which is the first place to make ifql popular.

**Comment by nathanielc** [comment]
@szibis FYI, I have implemented top/bottom in this PR https://github.com/influxdata/ifql/pull/229

With top/bottom I added implementation for highestMax etc functions. Since it was all pure IFQL it was quite easy to add in. See [this](https://github.com/influxdata/ifql/pull/229/commits/f3c950f50d92103b5ff83f3bb5cea204272e9215#diff-545e83ba31f10ef97281818ce92f26c5R13) for the relevant IFQL code.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/318)
