### ISSUE TITLE
Support Calendar Time Operations

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#201]
https://github.com/influxdata/influxdb/issues/2071
https://github.com/influxdata/influxdb/issues/6723
https://github.com/influxdata/influxdb/issues/7530
https://github.com/influxdata/influxdb/issues/8183
https://github.com/influxdata/influxdb/issues/3991
https://github.com/influxdata/influxdb/issues/8298 (support gaps in query range)

Possibly model after SQL time funcitons https://msdn.microsoft.com/en-us/library/ms186724(v=sql.90).aspx

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/317)
