### ISSUE TITLE
Add ASAP function

### ISSUE THREAD

**Issue by szibis** [influxdata/ifql#208]
ASAP: Prioritizing Attention via Time Series Smoothing

https://github.com/stanford-futuredata/ASAP

Graphite implementation:

https://github.com/wyndhblb/graphite_asap

and go-lang implementation:

https://github.com/errx/go-asap

**Comment by nathanielc** [comment]
@szibis Thanks for the suggestion! Is this something you would be interested in adding to IFQL? Adding the function is quite simple, you can start by copying the files `functions/sum.go` and `functions/sum_test.go` Then implement the function for the float data type only.

Note that the https://github.com/errx/go-asap implementation has no license specified which probably means we can't use it unless the owner adds one.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/310)
