### ISSUE TITLE
IFQL Meta queries should return normal tables, allowing for further manipulation

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#209]
IFQL Meta queries return data about the schema of a table. The returned result should be a table itself so it can be further transformed.

See for  some use cases https://github.com/influxdata/influxdb/issues/5548 https://github.com/influxdata/influxdb/issues/5668

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/309)
