### ISSUE TITLE
Support fill(previous) where first value is missing and outside of time bounds.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#210]
https://github.com/influxdata/influxdb/issues/5943

**Comment by robertsLando** [comment]
Is there any news or workaround for this feature?

**Comment by nathanielc** [comment]
Nothing yet. Have a look here for possible design of fill and interpolate. https://github.com/influxdata/ifql/issues/255#issuecomment-386575819

**Comment by robertsLando** [comment]
@nathanielc  Maybe mine could be seem a stupid answer but here is how I have think to workaround this.

After I get the result from a query using `fill(previous)` I check first rows value of result and if it is null I make another query that uses `first(value)` to get the first value before the start date of the first query and with the result of the second query I fill the null values until I find a not null value (or I reach the end of result rows)

**Comment by robertsLando** [comment]
What about this workaround? Use 2 separate queries:

1. Query a specific time range and use the `fill(previous)` function
2. Check the result rows of first query, if first row value is null make another query that fetches the last value before the start date of the first query time range: `select last(value) from (select * from <measurement> where time < <start_date>)`. With the result of this second query start fill null values of first query until you find a not null value (or you reach the end of the result rows)

**Comment by robertsLando** [comment]
I have successfully implemented my workaround, here some code from it (I'm using influx for nodejs)

```javascript
...
//if the result from the first query with fill(previous) returns 0 rows
if(rows.length == 0) {
            //How many points should I get here ?
            var points = Math.floor((end.getTime() - start.getTime()) / (interval * 1000)) || 1;
            var offset = start.getTime();
            for(i=0;i<points;i++)
              rows.push({time: offset + i*interval*1000, value: null});
          }
           //first row value is null (and maybe also next values so fetch las value before (using my second query)
          if(rows[0].value == null){
            self.getLastBeforeDate(topicParts, start, function(err, last){
              if(err)
                callback(err, null);
              else{
                i=0;
                while(i < rows.length && rows[i].value == null)
                  rows[i++].value = last.value;

                callback(null, rows);
              }
            })
          }
...
```

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/308)
