### ISSUE TITLE
What to do about COUNT with missing data?

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#211]
https://github.com/influxdata/influxdb/issues/6412
https://github.com/influxdata/influxdb/issues/6967

Do we create series for all tag in the index? How could we do that in a deterministic manner.

**Comment by nathanielc** [comment]
Consider this use case:

> Alert when I see more than two points in an interval and return to ok on the first interval with fewer than 2 points

This query can be written like this in IFQL (using a mock alert function since its design hasn't been nailed down yet):

```javascript
interval = 1m

from(db:"telegraf")
     |> filter(fn: (r) => r._measurement == "mymeasurement")
     |> window(every:interval)
     |> count()
     |> alert(crit: (r) => r._value > 2)
```

So the query is straightforward, but the implementation may not be. We need to consider how windowing operates under the hood such that it is capable of emitting empty windows when no data has arrived.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/307)
