### ISSUE TITLE
Time literal arithmetic 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#216]
https://github.com/influxdata/influxdb/issues/6881
https://github.com/influxdata/influxdb/issues/8153

Should be able to convert between times, durations and ints.

**Comment by jsternberg** [comment]
This one too: influxdata/influxdb#8418

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/303)

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/305)
