### ISSUE TITLE
Add support for increase function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#217]
https://github.com/influxdata/influxdb/issues/7076

Probably looks something like this:

```
increase = (table=<-) => 
    difference(table, nonNegative:true)
        |> cumulativeSum()
```

See also https://prometheus.io/docs/querying/functions/#increase.

**Comment by nathanielc** [comment]
@sscarfone Thanks for the detailed requirement. We will ensure it works this way instead of just dropping the `3` value entirely.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/302)
