### ISSUE TITLE
add ability to select measurement in from node

### ISSUE THREAD

**Issue by russorat** [influxdata/ifql#239]
seems like you should also be able to specify the measurement you are interested in from the `from` node. It would be a handy shortcut instead of having to specify a `filter`.

**Comment by nathanielc** [comment]
I like the suggestion and nearly everyone who uses IFQL the first time has similar feedback. The problem is everyone wants to combine from with some different aspect (i.e. fields vs measurements vs tags). 

I think we should probably create some helper functions as its really easy to do, for example:

```
// need a better name than getData but the idea still holds
getData = (db,measurement) => from(db:db) |> filter(fn:(r) => r._measurement == measurement)
```

The question is which ones are helpful.

**Comment by russorat** [comment]
the reason i was expecting to be able to define it in the `from` node is because with influxql, i'm able to say `select * from database.rp.measurement`. you can't specify tags the same way in influxql which is why i would keep that separate.

**Comment by nathanielc** [comment]
With IFQL we are moving away from the concept of a measurement, and a measurement is really just a tag. So I don't want to change the `from` node to accept a measurement argument as that is not really part of its data model. That said we want to make the transition easier, hence shipping IFQL with some helper functions that work more like influxql seems like a good idea. I just don't have a good grasp on what those functions should be.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/285)
