### ISSUE TITLE
Inconsistent results with filter function

### ISSUE THREAD

**Issue by pauldix** [influxdata/ifql#249]
Here are two examples that I would expect to return the same results:

```
from(db:"mydb")
  |> filter(fn: (r) => r.host == "server0")
  |> last()
```

```
from(db:"mydb")
  |> filter(fn: (r) => {return r.host == "server0"})
  |> last()
```

When run using the IFQL command, the first example returns only blocks that have values matching the filter function. The second example returns those same blocks, but also an empty block for every series that doesn't match the filter function.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/277)
