### ISSUE TITLE
Query with `range(start:0)` does not complete

### ISSUE THREAD

**Issue by rbetts** [influxdata/ifql#252]
Using the sandbox this query, using a `range(start:0s)`, does not complete:

  > q=from(db: "telegraf") |> filter(fn: (r) => r["_measurement"] == "cpu" AND r["_field"] == "usage_user") |> range(start:0s) |> group() |> sum()

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/274)
