### ISSUE TITLE
Using range and limit together doesn't give the result I expected

### ISSUE THREAD

**Issue by sjoerdmaessen** [influxdata/ifql#263]
I was expecting the following query to return 1 result, instead I get all results within the range:

`curl -XPOST --data-urlencode \
'q=from(db:"database_name")
    |> range(start:-150h)
    |> group(by: ["xxx"])
    |> limit(n:1)' \
http://project.ebox:8093/query`

The reason I also supply a range is because I else get an error message: 
"Error executing query failed to create physical plan: unbounded queries are not supported. Add a '.range' call to bound the query."

What I'm eventually trying to do is to compare values from the 2 latest results from xxx, being able to select the last result seemed like a good starting point.

**Comment by nathanielc** [comment]
@sjoerdmaessen The limit applies to each group, which is what I believe you want since you want to compare results from each `xxx`.

**Comment by sjoerdmaessen** [comment]
Thank you for your response. Yes, thats makes perfect sense. 

However I get the following result:

`measurement,xxx=abc value=0.00000031 1518998400000000000
measurement,xxx=abc value=0.00000034 1518998400000000000
measurement,xxx=abc value=0.00000024 1518998400000000000
measurement,xxx=abc value=0.00000034 1518998400000000000
measurement,xxx=abc value=0.09507 1518998400000000000
measurement,xxx=def value=0.00000001 1518998400000000000
measurement,xxx=def value=0.00000001 1518998400000000000
measurement,xxx=def value=0.00000001 1518998400000000000
measurement,xxx=def value=0 1518998400000000000
measurement,xxx=def value=0.00000001 1518998400000000000
measurement,xxx=ghi value=0.001811 1518998400000000000
measurement,xxx=ghi value=0.00000097 1518998400000000000
measurement,xxx=ghi value=0.00000097 1518998400000000000
measurement,xxx=ghi value=0.00000097 1518998400000000000
measurement,xxx=ghi value=0.00000097 1518998400000000000
...
`

So I get 5 results per group. To make it even more interesting, when I supply limit(n:2) I get 10 results per group and with limit(n:3) I get 15 results per group. So it seems to be increasing the results with 5. 

It's definitely a possibility I'm doing something wrong here but I don't understand what that would be at this point.

**Comment by nathanielc** [comment]
Yeah, that seems odd, I'll investigate and let you know. Meanwhile can you share a small subset of the data? Maybe there is an extra tag that is getting ignored somehow.

**Comment by sjoerdmaessen** [comment]
I have done my best to create some test dataset.

On the server:
---------------
CREATE DATABASE test
use test
INSERT example,xxx='abc' field1=101,field2=81
INSERT example,xxx='abc' field1=102,field2=82
INSERT example,xxx='abc' field1=103,field2=83
INSERT example,xxx='abc' field1=104,field2=84
INSERT example,xxx='abc' field1=105,field2=85
INSERT example,xxx='abc' field1=106,field2=86
INSERT example,xxx='abc' field1=107,field2=87
INSERT example,xxx='abc' field1=108,field2=88
INSERT example,xxx='abc' field1=109,field2=89
INSERT example,xxx='abc' field1=110,field2=90
INSERT example,xxx='abc' field1=111,field2=91
INSERT example,xxx='abc' field1=112,field2=92
INSERT example,xxx='def' field1=101,field2=81
INSERT example,xxx='def' field1=102,field2=82
INSERT example,xxx='def' field1=103,field2=83
INSERT example,xxx='def' field1=104,field2=84
INSERT example,xxx='def' field1=105,field2=85
INSERT example,xxx='def' field1=106,field2=86
INSERT example,xxx='def' field1=107,field2=87
INSERT example,xxx='def' field1=108,field2=88
INSERT example,xxx='def' field1=109,field2=89
INSERT example,xxx='def' field1=110,field2=90
INSERT example,xxx='def' field1=111,field2=91
INSERT example,xxx='def' field1=112,field2=92

As a client:
-----------
curl -XPOST --data-urlencode \
'q=from(db:"test")
    |> range(start:-170h)
    |> group(by: ["xxx"])
    |> limit(n:1)' \
http://project.dev:8093/query

Client output:
--------------
measurement,xxx='abc' value=101 1519517485505332075
measurement,xxx='abc' value=81 1519517485505332075
measurement,xxx='def' value=101 1519517485638177931
measurement,xxx='def' value=81 1519517485638177931

Now interesting enough I get 2 values per group, with a limit of 2 I get 4 values per group

**Comment by nathanielc** [comment]
Looking into to this I know what is going on. The data has two fields meaning that the tag set includes `[xxx, _field]`. When the limit+group is pushed down into the read operation the limit is applied to each series. The bug is that the limit is not reapplied for the correct grouping once the storage read completes. This is related to this bug #244

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/267)
