### ISSUE TITLE
Formalize concept of Block Key

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#290]
Currently a block is uniquely identified by this interface:

```
type BlockMetadata interface {
	Bounds() Bounds
	Tags() Tags
}
```

This means that blocks are identified by their time bounds and their tag bounds.

 Knowing what the block key is for a given operation within a query is helpful since it dictates how the data is partitioned an those which datasets the operations operate on.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/263)
