### ISSUE TITLE
Remove concept of Kind from table columns

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#294]
The current implementation makes a distinction between three different kinds of columns:

* Time - the time column
* Tag - a column that is always a string and can be grouped on
* Value - a column that is any type and is aggregated by default

I think these distinctions actually make the data model harder to understand and do not provide much value. 

When writing data to InfluxDB you specify the time, tags and fields on the data. These are useful constructs when writing data because they inform how the data is to be indexed and stored. Once the data is read out of the storage tier and into IFQL, there is no longer any difference in the columns. We do not have indexes an some columns vs other or anything like that. All columns are equal, as such the query engine/language should treat them as such.

The proposal is to treat all columns as equal, this provides the greatest flexibility and embodies the principal of least surprise. As it stands today some operations can only be applied to certain kinds of columns, so the user will be found asking themselves why they can't perform those actions on the other columns.

What will it mean to remove the concept of column Kind from the current engine?

* All functions will need to be explicit about which columns the function should operate on.
   For example: ` |> sum(cols:["usage_idle","usage_system"])` or `|> derivative(cols:["bytes_in", "bytes_out"]). The default list of columns will be `["_value"]`. 
* All functions should be well defined for operating on any column. For example the current group implementation assumes the `by` columns are all tags. There is no need for this assumption. Another example is the `distinct` function should work for columns of type `time`.

The only place where it will be important to then instruct the engine which columns are tags vs values is when data is written back to the database. This can be done at the output call site.

```
...
 |> outputBucket(
    time:"_time",
    tags:["host", "region"], 
    fields:["usage_idle", "usage_system"],
)
```

**Comment by aanthony1243** [comment]
The only concern I could imagine--but maybe this is a _feature_--but this opens the door for users to convert tags to features and back to tags.  We should probably make sure @stuartcarnie and some other core team members put some thought into whether or not this will thrash the index in weird ways.  

Otherwise---I love this, it's a great improvement.

**Comment by nathanielc** [comment]
Yes, its a feature and it will be explicit. Meaning the user will be in direct control of what is a tag or a field when written back to the DB so its no different then the normal write endpoint where the user chooses.

**Comment by pauldix** [comment]
I think this is a great improvement. The only other query type I'd like to actually come up with an example for is a query where we want to downsample all data and write it back to the database. In that case we'd be using wildcards for many things. Can you write up an example of that if you're producing 1h min, max, first, last, sum, count summaries?
