### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#296]
There are three different contexts in which errors can arise when executing a query:

1. With just the text of the query
2. With text of the query and the data schema
3. With the text, schema and values of the data.

How should we handle errors are each of these layers?

The first layer is straightforward, when ever a user submits an invalid query text reject it and return an error. 

The second is also clear, since no data will be able to be processed, kill the query and return the error.

The third has at least two ways it could be handled. Log the error and increase a counter and move on. Alternatively kill the entire query.

Are there other methods that apply to the third layer? If not then is seems like a simple global toggle for the query would be sufficient to allow users to choose their desired behavior.

**Comment by pauldix** [comment]
I'm thinking of this language more and more as a lightweight scripting language in addition to a query language. So there are some data munging tasks that I'd like to be able to do in the language itself.

For example, if I have string fields (or tag values) and I want to modify them or grab parts of them and then maybe do conversions. There are errors that could happen during data munging that I would want to move past by setting some sort of default value or something like that, but continue execution of the script.

Another thing to think about is that "logging the error" is something we should think about for both interactive queries and background queries. For interactive queries we can simply send the response to the user. For the background queries, we'll need to have some sort of log that is accessible via the API (which is mentioned in the Tasks writeup). But do we want interactive ones to both log to something and send a response?

**Comment by aanthony1243** [comment]
in the CI world, there's a trigger like `if error rate is > 10% then ERROR else WARNING`

considering the time-series use-case and the possibility of mal-formed data coming across frequently, they may want some built in support to detect that something has gone _very_ badly in their pipeline.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/261)
