### ISSUE TITLE
Timezone support for window function

### ISSUE THREAD

**Issue by floppywaste** [influxdata/ifql#298]
If I understand correctly the window function is somehow equivalent to *group by time* in INFLUXQL, which supports timezones and offsets. Is it somehow possible to use timezones with the window function?

**Comment by nathanielc** [comment]
You are correct, the window function does not yet support timezones, but is does support offsets via the `start` parameter.

**Comment by nathanielc** [comment]
We absolutely plan to support timezone along with other Gregorian calendar operations, see https://github.com/influxdata/ifql/issues/201 for details. 

As for when I can't say specifically, except that the we plan for the first official release of IFQL will support the features already present in InfluxQL.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/260)
