### ISSUE TITLE
New function: outputHTTP

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/ifql#302]
Options:

- `addr` (string): Full string of address, e.g. `http://foo.example.com:12345/api/v1/bar`; must not include URL parameters
- `urlParams` (map[string]string): URL parameters to add to the request
- `method` (string): We could either require it to be one of "GET", "PUT", "POST", "DELETE", "HEAD", or "OPTIONS"; or we could just require it to be set and trust that it is one of those well-known methods or one of the lesser-known methods.
- `headers` (map[string]string): Headers to add to the request

Example:

```
from(db: "my_db")
    |> range(start: -1h)
    |> max()
    |> outputHTTP(
      addr: "https://api.example.com/alert",
      method: "POST",
      headers: {"My-Auth-Token": "ABC123"},
    )
```

The outgoing request should also have a default `User-Agent` header of something like `ifql.outputHTTP`, but if a `User-Agent` header is supplied in the function call, the supplied UA should take precedence over the default.

**Comment by nathanielc** [comment]
The name should be camel case so `outputHTTP`. 

I think for simplicity we should leave the encoding bits out of scope. Meaning lets hard code the body to encode the data using line protocol for now. We can come back to how to express different encoders later.

Also I'd expect the `outputHTTP` function to accept a table argument instead of having a `toString()` function.

So something like this 
```
from(db: "my_db")
    |> range(start: -1h)
    |> max()
    |> outputHTTP(
  addr: "https://api.example.com/alert",
  method: "POST",
  headers: {"My-Auth-Token": "ABC123"},
)
```

**Comment by docmerlin** [comment]
I've also added `timeout` to the params which should be a `time.Duration` and be ignored when it is less than or equal to 0.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/258)
