### ISSUE TITLE
Define syntax for directives

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/ifql#305]
This isn't about implementing any particular [directive](https://en.wikipedia.org/wiki/Directive_(programming)), but defining how to state a directive in IFQL. 

Directives specify intent of how the particular IFQL script is run. For instance, if you were writing a downsampling job in IFQL, you could use crontab syntax to specify how often it should run. As another example, there could also be a "strict" directive that disallows overwriting or shadowing universal variable.

As a strawman proposal, I suggest that there is a new function `directive` that takes a single map argument. The directive must be the first expression in the file.

```
directive(d: {
  cronSchedule: "0 0 * * *", // Run every day at midnight.
})

from(db: "my_db") |> ...
```

Some preset directives, like the "strict" suggestion would be standard across IFQL. Other directives, like `cronSchedule` in the example, would only take effect on certain IFQL execution engines.

**Comment by nathanielc** [comment]
I like this initial proposal. What is the value of having a single map as opposed to multiple keyword args?
Using many keyword arguments removes the extraneous `d` argument.

```
directive(
  cronSchedule: "0 0 * * *" // Run every day at midnight.
)
```

**Comment by mark-rushakoff** [comment]
I think keyword arguments make sense. Does IFQL support functions with arbitrary keywords, or would `directive` be a special case?

I initially used a map under the assumption that certain directives would only apply to certain execution engines. `cronSchedule` probably doesn't make sense in the REPL, so it would be a frustrating experience to paste in some code and then have it be rejected because the REPL's implementation of `directive` doesn't support the `cronSchedule` keyword.

**Comment by mark-rushakoff** [comment]
If directive `foo` is introduced in v1.1 (i.e. not present in v1.0), what happens when I run IFQL with `directive(foo: "x")` in v1.0?

I would prefer to see new directives be backwards compatible, but I suppose there is the obvious workaround of just removing the unrecognized directive.

**Comment by nathanielc** [comment]
In general I do not think we can support seamless downgrades. The above is true for any function not just the `directive` function.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/257)
