### ISSUE TITLE
Allow numeric literal to be safely coerced to concrete numeric types

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#309]
From the Spec:

Numeric literals may be integers or floating point values.
Literals have arbitrary precision and will be coerced to a specific type when used.

The following coercion rules apply to numeric literals:

* an integer literal can be coerced to an "int", "uint", or "float" type,
* an float literal can be coerced to a "float" type,
* an error will occur if the coerced type cannot represent the literal value.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/255)
