### ISSUE TITLE
Specify type inference rules

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#315]
A type defines the set of values and operations on those values.
Types are never explicitly declared as part of the syntax.
Types are always inferred from the usage of the value.

Type inference needs to enable polymorphic behavior of functions, and allow for describing such behavior in function signatures.

For example we would like to be able to call a function `alert` who's message argument is either a string or a function that returns a string and accepts a record as its only parameter.

```
m = "Message prefix"

alert(message: (r) =>  "{m}: {r.host} is {r._value}")
alert(message: m)

alert(message: 42) // this would still need to be invalid
```

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/249)
