### ISSUE TITLE
SPEC: date and time types

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/ifql#337]
The section currently reads:

> A date and time literal represents a specific moment in time. It has a date part, a time part and a time offset part. The format follows the RFC 3339 specification.

> ```
> date_time_lit     = date "T" time .
> date              = year_lit "-" month "-" day .
> year              = decimal_digit decimal_digit decimal_digit decimal_digit .
> month             = decimal_digit decimal_digit .
> day               = decimal_digit decimal_digit .
> time              = hour ":" minute ":" second [ fractional_second ] time_offset .
> hour              = decimal_digit decimal_digit .
> minute            = decimal_digit decimal_digit .
> second            = decimal_digit decimal_digit .
> fractional_second = "."  { decimal_digit } .
> time_offset       = "Z" | ("+" | "-" ) hour ":" minute .
> ```

One notable difference in this grammar vs RFC3339 is that RFC3339 is more explicit about the valid ranges for months, days, hours, minutes, and seconds. The IFQL spec should more clearly express that valid months are 01-12, valid hours are 00-23, etc., even if that is just referring to appropriate sections in the RFC.

That is assuming IFQL needs to keep dates and times. I assume it does, but it's hard to tell from the spec whether and how the query language uses date times. Is a datetime the only valid type, or is it valid to just have a date or just have a time?

What are the valid contexts for a `date_time_lit`? Is `epoch = 1970-01-01T00:00:00Z` a valid variable assignment? 

I think we have the option to simplify the grammar by eliminating date and time literals, and just require a function like `dateTime("1970-01-01T00:00:00Z")`.

**Comment by nathanielc** [comment]
>One notable difference in this grammar vs RFC3339 is that RFC3339 is more explicit about the valid ranges for months, days, hours, minutes, and seconds. The IFQL spec should more clearly express that valid months are 01-12, valid hours are 00-23, etc., even if that is just referring to appropriate sections in the RFC.

+1

> Is a datetime the only valid type, or is it valid to just have a date or just have a time?

Not sure, right now only a datetime is valid. Maybe when we go to implement #201 it will be more clear if we need them. Either case it should be an easy additive change that is backward compatible.

> Is epoch = 1970-01-01T00:00:00Z a valid variable assignment?

Yes that is valid. Mostly it will come up in the context of the `range` function where you want to specify time bounds on a query.

> I think we have the option to simplify the grammar by eliminating date and time literals, and just require a function like dateTime("1970-01-01T00:00:00Z").

I rather have a more complex grammar in order to provide a time literal that simplifies queries.

```
    |> range(start:2018-01-01T00:00:00Z, stop:2018-05-01T00:00:00Z)
```
vs 
```
    |> range(start:dateTime(t:"2018-01-01T00:00:00Z"), stop:dateTime(t:"2018-05-01T00:00:00Z"))
```

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/221)
