### ISSUE TITLE
SPEC: disallow leading zeroes for floating point literals

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#339]
I think we should disallow a leading zero for floating point literals. It's inconsistent with the parsing for integers and I think we can change the specification to this:

```
float_lit = decimals "." [ decimals ] |
    [ "0" ] "." decimals .
decimals  = decimal_digit { decimal_digit } .
```

That would still allow you to do `0.2`.

This is a minor nitpick.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/219)
