### ISSUE TITLE
SPEC: support for calendar-aware duration literals

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#341]
I think we should formally introduce the `M` and `y` duration specifiers. This is something we miss in influxql because time zones were added too late in the language to make them usable, but defining how these work and then declaring them not implemented would allow for a future expansion of the language.

A year is not the same as 52 weeks. 52 weeks doesn't consider for time zone and leap year differences and it also adds up to 364 days, not even 365. Because of leap years, saying "use 365 days" does not actually give the person what they want which is the last year. If a person wants the last year, it helps us a lot to _know_ they want the year so we can adjust it for them using calendar-aware range functions.

This is similar to month. A common request we get with influxql is the ability to aggregate January, February, etc. We should add the month duration unit so that we don't lose this valuable information and can make a future expansion.

We should not implement any of these without including the calendar-aware functionality. They would  be left as a placeholder in the spec until we can implement that functionality.

**Comment by jsternberg** [comment]
I think we need to change the definition of a duration then. As an example:

```
from(db: "telegraf") |> range(start: -5y) |> group() |> window(every: 1y) |> mean()
```

In this example, you are finding the mean value for every year. We would of course filter this as needed for a specific measurement/field, but that's not relevant to the example.

This is a request we have gotten before. influxdata/influxdb#8183. That's the reason why I think we need to build this into the language itself because we can't do this in influxql because the duration literal gets transformed into an int64. By the time it gets to the grouping code, the grouping code doesn't know that it should be grouping by every month rather than every 30 days.

Time zone support is very hard to add after the fact.

**Comment by jsternberg** [comment]
I have updated this to "calendar-aware" so that it matches with the actual goal better. Time zones are part of this, but I think this more accurately describes what is desired.

**Comment by nathanielc** [comment]
Changing the definition of durations to be a flexible amount of time depending on the specific dates makes it really difficult to reason about durations. I think we should use a different mechanism to represent calendar durations, see for more details https://github.com/influxdata/ifql/issues/201

Maybe you can drop some of your ideas on that issue.

**Comment by jsternberg** [comment]
I'm not sure I agree with that. I think the problem is the definition of duration is wrong to begin with. A duration is a range of time, but not necessarily a fixed range of time. Keeping the definition of duration as a range of time is likely more intuitive than trying enforce a programmer's perspective on what a duration is and using this definition allows the following queries to work, be easily understood, and intuitive.

```
from(db: "telegraf") |> range(start: -5y) |> group() |> window(every: 1y) |> mean()
from(db: "telegraf") |> range(start: -1y) |> group() |> window(every: 1M) |> mean()
from(db: "telegraf") |> range(start: -1M) |> group() |> window(every: 1d) |> mean()
```

The internal implementation is going to be the same for this type of query regardless of whether you have a duration literal for it. If you were to window by a month, you would likely need something like `window(every: month())` and the internal implementation is going to be the same anyway, but you won't be leveraging the existing literal mechanisms you already have.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/217)
