### ISSUE TITLE
SPEC: object types should be renamed to record types and be ordered

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#345]
This covers a few different sections of the spec. In the data model section, a record is listed as a "tuple of values" and a table is listed as a "set of records with a common set of columns and a partition key".

While the table definition is correct, I don't think a record is necessarily as simple as just a tuple. Most of the functions take a record as an argument and the record that is passed in is a set of key/value pairs for that single entry. While those keys are tied to the columns from the table, I think a record would be more accurately described as a tuple of key/value pairs. I think it would also make some other parts of the spec easier to follow and more useful.

Object literals could then be described as record literals since that's what they are. When I have the map function, I am taking in a record as an argument and returning a new record (the optimizer may feel free to mutate the inserted record if that record isn't being used elsewhere though). That way, this makes sense:

```
map(fn: (r) => {val1: r._value * 2, val2: r._value * 3})
```

I also believe records should be [ordered](https://stackoverflow.com/questions/1084146/what-is-the-difference-between-an-ordered-and-a-sorted-collection) (not sorted). Columns themselves are ordered and this will make it much easier to develop the transpiler since the transpiler can ensure that the types are mapped in the correct order so the output gets returned correctly. Otherwise, the return value of the above example is indeterminate since who knows which column will be first. Will `val2` be the first column or will `val1`?

Allowing the tables to be ordered also makes it easier to implement something like `left_join`. The table that is left most is the one that gets joined to. It seems to make more sense to me in a language where ordering does matter.

**Comment by nathanielc** [comment]
>  I think a record would be more accurately described as a tuple of key/value pairs. I think it would also make some other parts of the spec easier to follow and more useful.

Agreed, submit a PR for this change.

> Object literals could then be described as record literals since that's what they are.

This is not always the case, for example the objects passed to the join tables argument is not a record, nor is the object passed into the join function. There are other planned cases as well. In general it is useful to have a generic map/object type without requiring that every instance of a map be thought of as a record.

> I also believe records should be ordered (not sorted). 

This is an interesting idea. I think you are right that saying that the objects are ordered is valuable. It would enable distinguishing left vs right in joins etc.

 In contrast order has no meaning anywhere else in the language (except for arrays). Meaning why does it matter what the column order is? You always refer to columns by their names anyways. The order of the columns would just be a presentation layer thing, not part of the data model itself.

**Comment by jsternberg** [comment]
It would likely be a small thing to add the ordering and, while this isn't a good argument from a "pure" perspective, it would likely be needed for the transpiler. I also imagine that a pretty early request will be a person who wants to specify the output order of the columns from the CSV and just making it ordered by default would be helpful.

I do agree with you that the arguments for the join table are not a "record". I think there's a complete overlap with the functionality, but using the word "record literal" might be confusing. Maybe we should keep calling it an object literal, but then define records as a single object? That way, they are functionally the same, but it is easier to describe and they are a unified concept within the language and AST.

**Comment by jsternberg** [comment]
Also, it would be possible to specify the order using a function and an array because they are ordered, but I think it would be syntactically easier and more natural to just make the records/objects ordered.

**Comment by nathanielc** [comment]
>it would likely be needed for the transpiler.

Can you give a concrete example of this? I would consider it a bug if this is the case.

**Comment by jsternberg** [comment]
While looking at the spec to try updating it for this change, I encountered a rather strange problem that I think we need to resolve if we want to make the object literals ordered.

What happens with duplicate keys? If there are duplicate keys, would they overwrite the old one or become another column with an identical name? How would they get indexed when you needed to access them? We could allow indexes based on both name and column number and make it so the name would always access the first one, but we have to define it if that's what we're doing.

Additionally, how would this work out with the new behavior for `map()` with `mergeKey: true`? Would the new entries in the map be appended to the end or how would it be controlled? Would the old keys be overwritten or erased and appended to the end?

I do still like the idea of controlling the ordering, but I think there's a few cases we need to consider before making this change so the spec is specific.

**Comment by nathanielc** [comment]
Duplicate keys is an error.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/214)
