### ISSUE TITLE
SPEC: remove expression statements

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#349]
I think we should disallow expression statements and turn them into errors. I also think we should make it so that any unused variable is an error similar to Go. I think it works really well for Go and makes maintaining code a lot easier. For ifql, we're making a new coding language even if it isn't necessarily turing complete and so the same practices still apply.

Expression statements are described as this:

> An expression statement is an expression where the computed value is discarded.

Since expressions are defined earlier as pure functions, there's no point in computing a value just to discard it and it would always be an error.

I do think we can modify this section though to say something like:

> An expression statement is an expression that is terminated by an action node.

And then we would define an action node as one of the special "action" functions. The examples are `yield()` and `write()`. You can then say that all top level portions of the ifql document are either declarations or statements, but the last expression is automatically terminated with a `yield()` if it doesn't have any other action node.

So the following would not be allowed:

```
from(db: "telegraf")
from(db: "telegraf")
```

Because the first expression there is an expression and not a declaration or statement and it doesn't do anything. But, the last one does do something because it is automatically wrapped in a `yield()`.

**Comment by nathanielc** [comment]
This would require every query to contain a `yield` function call. So far that has not been the design, we want single statement queries to be easier to read/write and so we do not require a yield on those queries.

In either case removing the ExpressionStatement from the grammar is not the correct solution. Which ever system is executing the IFQL script can disallow them as part of that environment. For example IFQL has both an interpreter and a compiler, currently the compliler does throw an error if an expression statement is used. The compiler is used in the context of applying functions on the record data, like filter and map functions. The interpreter is used when executing the entire script.

**Comment by jsternberg** [comment]
I think you misinterpreted what I wrote, but I think there's a common thread that both of us agree on, but just using different terms.

> And then we would define an action node as one of the special "action" functions. The examples are yield() and write(). You can then say that all top level portions of the ifql document are either declarations or statements, but the last expression is automatically terminated with a yield() if it doesn't have any other action node.

So I don't think that we should require a `yield()` to be explicit, but I think that it should be an error for anything other than the last statement. Basically, anything that wouldn't auto-execute should be an error and we should specify in the spec that it would be an error.

If we agree that this should be illegal:

```
from(db: "telegraf") |> range(start: -5m) |> max() // this statement is illegal because it is not the last statement (so it doesn't auto-execute) and it does not get used
from(db: "telegraf") |> range(start: -5m) |> min() // this statement is fine because it is the last statement
```

Before we talk about specific language, should the above query be allowed in the context of a compiled query?

**Comment by nathanielc** [comment]
The above query is illegal.

**Comment by jsternberg** [comment]
So I think there's too ways to make that statement illegal. The way I favored here was by making certain nodes terminating nodes and I called them "action nodes". They are things that take a result and have a mutable consequence (non-pure functions).

I think you gave me an idea though for some better language. The better way to say it to use the word "expression statement", but to say in the documentation something like this:

> Expressions inside of an expression statement must be terminated by an action node. If an expression statement is the last statement in a program and it is not terminated by an action node, an implicit `yield()` is added to the expression.
>
> An action node is any node that performs an action and terminates the expression chain. The currently supported action nodes are `yield()` and `write()`.

This way, the standard behavior of using a single query still works, but it explicitly disallows the above query because one of the two expression statements is not the last statement in the program and it is not terminated by an action node.

**Comment by nathanielc** [comment]
We agree on behavior, I think were we disagree is on solution. There are different levels at which we can solve this. Your solution is to use the language grammar to make such statements illegal, meaning that the script would not even parse. That is too aggressive, it would require adding an explicit grammar production rule for action nodes, and would mean that adding new action nodes would require updating the parser. 

My solution is to enforce the behavior within the execution of the query specification. This allows us to have the same behavior independent of source language of the query specification. Currently the query planner implements this behavior.

**Comment by jsternberg** [comment]
I think that's compatible with my last comment. I just want a line in the spec saying expression statements can't be used without an action node at the end.

If we agree on the behavior, it might be best for me to try coming up with the language I like and then we can discuss that.

I don't think it should be enforced with the language grammar and I don't think it would be possible to enforce it with the language grammar without making it too intrusive. The grammar shouldn't know what a terminating action node is and it would be complicated to include the auto-yield functionality.

So we likely agree on solution too so I'm going to try and create language for this that is suitable for the spec.

**Comment by nathanielc** [comment]
>  I just want a line in the spec saying expression statements can't be used without an action node at the end.

> The grammar shouldn't know what a terminating action node is and it would be complicated to include the auto-yield functionality.

These statements contradict one another, an `expression statement` is purely a concept of the grammar.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/210)
