### ISSUE TITLE
SPEC: version the response format

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#351]
I think we should specify a mechanism for versioning the response format that would be requested using the `Accept` header. HTTP media types allow for [specifying parameters](https://godoc.org/mime#ParseMediaType) that can be useful when creating a versioned API. I think we should just assume that we are going to need to update the format at some point and be careful by adding something like a version to the parameters.

```
text/csv; version=1.0
```

Then, if we need to modify something like the data types by adding, removing, or renaming a data type, we can do so. If a person then goes and specifies they want a specific version, we can know that something like the unsigned type doesn't exist in version 1.0 and throw an error on serialization. While unsigned is supported in our version, it wasn't in version 1.0 of the current InfluxDB and I can imagine us adding stuff like geolocation support at some point. If we were to do that, we would have to add a new data type that a library may not necessarily know about or support.

If we never end up using this functionality then good for us, but I think it's important we add this early on so we don't have to staple it on later.

**Comment by jsternberg** [comment]
I personally think that would be good as it would allow us to make revisions to the response format. At the least, I'd like this to be considered.

Maybe we should create an informal list of things we think could happen that would require a version bump and then think, "What would be the best place to reflect that change?"

The API being versioned might be enough though. I hadn't considered that when I wrote this issue.

**Comment by goller** [comment]
@jsternberg the way to do this is not via headers, but, in a POST body

**Comment by jsternberg** [comment]
I think compelling arguments have been made that the API version should also control the response format so I'm going to close this.
