### ISSUE TITLE
SPEC: the dateTime response format should be a unix timestamp

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#352]
I think the dateTime response format should be a timestamp. It makes it easier for various languages to evaluate the timestamp in their own specific way.

I **strongly** believe that the `dateTime` datatype is very important and should be distinct and separate from the `long` data type. That is currently in the spec and I think that's very good. I don't think we should have the `dateTime:RFC3339` thing though. I don't think it adds much to the response format that's not easily done by a client library transforming the output.

Alternatively, if we want to still include the specification because it will make debugging without an extra tool easier, I think we should have `dateTime` by itself with no formatting string to be a unix timestamp and then allow an option for specifying the format of a `dateTime` as a query parameter.

**Comment by nathanielc** [comment]
I expect there will only ever be two encoding formats for the table data. One will be human readable text and the other will be a binary representation. We have chosen csv as the human readable text option, as such I think using a human readable date format make sense for the csv encoding.

That said, like you point out we have the flexibility to introduce new date formats as needed, which can be user specified. 


I expect that Apache Arrow will be used for the binary format FWIW.

**Comment by nathanielc** [comment]
This is not a breaking change. We can choose a default format now, and add options to specify the specific formats later.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/208)
