### ISSUE TITLE
SPEC: join function should be simpler

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#353]
The join function should be substantially simpler than it currently is.

Based on my use of the join function in the transpiler work, I find that join contains too much functionality and is very verbose for the most common use case because it seems to believe it a map function too. As an example, this is something I find strange:

```
val1 = from(...) |> ...
val2 = from(...) |> ...
join(tables: {val1: val1, val2: val2}, on: ..., fn: {val1: tables.val1, val2: tables.val2})
```

As can be seen, the function is just a copy of what I've already done when joining the tables.

Now I'm not sure the best way to do this because the function is sometimes useful. If you have an already joined stream, the function is needed to join the tables correctly with whatever names you want. But, the most common use case is probably the one above and it's a lot of typing for what should be obviously inferred. It seems to me that join and map should be separate functions so that you could instead do something like this:

```
val1 = from(...) |> ...
val2 = from(...) |> ...
val3 = join(tables: {val1: val1, val2: val2}, on: ...))
val4 = from(...) |> ...
join(tables: {val3: val3, val4: val4}) |> map(fn: (r) => {val1: r.val3.val1, val2: r.val3.val2, val4: r.val4})
```

This way, you still keep the existing mechanics and the optimizer can always combine them for efficiency, but the join command itself is optimized for joining tables and not responsible for also mapping them.

**Comment by nathanielc** [comment]
>This way, you still keep the existing mechanics and the optimizer can always combine them for efficiency, but the join command itself is optimized for joining tables and not responsible for also mapping them.

I would like this as well. My question is what do we do in the case that the join need to know how to rename columns because the two tables have columns that would conflict? Currently using a function is the solution to that problem as it allow the user to define explicitly what the new table structure is.

That said we may be able to create a helper function that can autocreate the join function so long as all column names are unique.

**Comment by jsternberg** [comment]
I gave a potential solution above for that problem. I think this also matches a bit more with SQL. So imagine you have two columns that you are joining.

```
user = from(...) |> ...
system = from(...) |> ...
join(tables: {user: user, system: system}) |> map(fn: (r) => r.user.count + r.system.count)
```

So just assume for the above that the `from()` statements creates a table with a `count` column, so they conflict. The join creates a table of two tables so you would just access it that way. It's similar to this:

```
SELECT user.id, system.id FROM user JOIN system ON user.id = system.id
```

We could also just make it so the function is optional and that it uses the default behavior if there is no function. If there would be a conflict, it throws an error and says "you must specify a function when column names conflict". I like the first better, but this one is also an option.

**Comment by jsternberg** [comment]
I think that's a good question and we should consider flattening the table when outputting the results. So if the above example with join was output as-is without the map, you would two columns with `user.count` and `system.count` as the results. It would be a special thing that yield does. We could also just have multiple columns with the same name like SQL does.

**Comment by nathanielc** [comment]
>  We could also just have multiple columns with the same name like SQL does. 

We can't do this, our representation of a record as an object does not allow it.

If a column name has a `.` value then you must use the `[]` index operators to get access to the value. Interpreting `.` within column names to indicate nested values seems like it would unneeded complexity and would cause problems for data which already has `.` in their column names.

it would have to look like this.
```
user = from(...) |> ...
system = from(...) |> ...
join(tables: {user: user, system: system}) |> map(fn: (r) => r["user.count"] + r["system.count"])
```

**Comment by jsternberg** [comment]
That's not what I meant. I only meant in relation to the encoded output. Within ifql itself, it would be a result of nested tables so you would do `r.user.count` or `r["user"]["count"]`. But, when you got to encoding the result to CSV or another format that is flat and can't do nested outputs, you would flatten it in the way I described or just use the same name. CSV doesn't care about that.

**Comment by jsternberg** [comment]
I also think we would have something special for the single column outputs that are `_value` to avoid having those be nested tables. We don't want to see `r.user._value` in my opinion. But I'm just spitballing ideas so nothing here is a formal proposal.

**Comment by nathanielc** [comment]
So you want to support nested tables then? How do you aggregate/select over a nested table? This seems like we are simplifying the join operation at the cost of other operations that now have to support nested tables. It seems simpler to have the join always return a flat table and then everything is always a flat table.

**Comment by jsternberg** [comment]
I'm not sure that's an accurate way to think about it. A nested table makes me think that you have a table (multiple rows) inside of a single row and I don't think we should allow that. It would be too complex and wouldn't really give us anything. I think we should allow nested records so something like this:

```
(1, (2, 3))
```

You still have a single row, but you have namespaced columns due to the nature of them being nested. Records should have access to the information about what each column is named which is a separate proposal I made to the spec.

If you attempt to run an aggregate on a record, then it would be an error like it currently is. So in the above, you wouldn't be able to run `mean()` on the second column. I also don't think we should have this function signature: `mean(cols:)`. I think it would be more flexible and also make this proposal possible if we were to pass in a function that way you could do this: `mean(fn: (r) => r.user.count)`.

I hope that makes sense. I think it matches with the SQL join operation more smoothly and I can try to flesh it out more and write the rules I'm thinking of in greater detail if you're interested in pursuing this possibility.

**Comment by nathanielc** [comment]
It still feels like a bad trade off, we remove the fn parameter from the join function and we have to add it to all aggregate/selector functions.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/207)
