### ISSUE TITLE
SPEC: convenience syntax for object/record literals

### ISSUE THREAD

**Issue by jsternberg** [influxdata/ifql#355]
A syntax I've noticed used a lot in different places is this, especially for joins.

```
val1 = from(...) |> ...
val2 = from(...) |> ...
join(tables: {val1: val1, val2: val2})
```

I would like us to explore and consider adding the following convenience syntax for this:

```
{val1, val2}
```

If an object literal is used with a single variable, it will use the name of the variable as the key and the actual variable for the value.

**Comment by nathanielc** [comment]
We can always make additional changes to the language and SPEC as we see fit. For now I want to specify as little as possible. As such let's not discuss syntactic sugar changes at the moment.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/206)
