### ISSUE TITLE
Flakey Test

### ISSUE THREAD

**Issue by docmerlin** [influxdata/ifql#371]
There is some flakeyness either in the tests or the testing framework.

compare 
https://circleci.com/gh/influxdata/ifql/606
and 
https://circleci.com/gh/influxdata/ifql/607

**Comment by nathanielc** [comment]
Looking at the test failure it appears that query/execute/partitionKey.Equal is not a correct. This test will be fixed by updating that function.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/236)
